config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'static_pages#top'
  get '/signup', to: 'users#new'

  # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  # 出勤社員一覧
  get 'working_employee_list', to: 'users#working_employee_list'
  
  # 拠点
  get 'bases', to: 'bases#index'
  get 'base_info', to: 'bases#base_info'
  get 'edit_base_info', to: 'bases#edit_base_info'
  get '/new', to: 'bases#new'
  post '/new', to: 'bases#create'
  delete '/destroy', to: 'bases#destroy'
  patch '/update_base_info', to: 'bases#update_base_info'
 
  
  #リソース
  resources :users do
    collection { post :import }
  end
  
  resources :users do
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      patch 'update_user_info'
      get 'attendances_edit_log'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
      patch 'onemonth_apply'
      get 'onemonth_approval'
      patch 'update_onemonth_approval'
      # 勤怠確認ページ
      get 'check'
      # CSV出力
      get 'attendance'
    end
    resources :attendances do
      member do
        get 'edit_overwork_request'
        patch 'update_overwork_request'
        get 'edit_overwork_approval'
        patch 'update_overwork_approval'
        get 'edit_changework_approval'
        patch 'update_changework_approval'
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  require 'rounding'
  require 'rails/all'
  require 'csv'
  has_many :attendances, dependent: :destroy
  # 1ヵ月勤怠申請状態（0:無 1:申請中 2:承認 3:否認）
  enum onemonth_application_state: { "なし" => 0, "申請中" => 1, "承認" => 2, "否認" => 3 }
  # 1ヵ月分の勤怠承認者選択
  enum month_authorizer: { "上長Ａ" => 1, "上長Ｂ" => 2 }
  
  # 「remember_token」という仮想の属性を作成します。
  attr_accessor :remember_token
  before_save { self.email = email.downcase }

  validates :name,  presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  validates :affiliation, length: { in: 2..50 }, allow_blank: true
  validates :basic_work_time, presence: true
  validates :designated_work_start_time, presence: true
  validates :designated_work_end_time, presence: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  # 渡された文字列のハッシュ値を返します。
  def User.digest(string)
    cost = 
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返します。
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続セッションのためハッシュ化したトークンをデータベースに記憶します。
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # トークンがダイジェストと一致すればtrueを返します。
  def authenticated?(remember_token)
    # ダイジェストが存在しない場合はfalseを返して終了します。
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
   # ユーザーのログイン情報を破棄します。
  def forget
    update_attribute(:remember_digest, nil)
  end
  
   # CSVインポート用
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      # IDが見つかれば、レコードを呼び出し、見つからなければ、新しく作成
      user = find_by(email: row["email"]) || new
      # CSVからデータを取得し、設定する
      user.attributes = row.to_hash.slice(*updatable_attributes)
      # 保存する
      user.save
    end
  end
  
  # 更新を許可するカラムを定義
  def self.updatable_attributes
    ["name", "email", "affiliation", "employee_number", "uid", "basic_work_time", "designated_work_start_time", "designated_work_end_time", "superior", "admin", "password"]
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :check, :edit, :update, :destroy, :edit_basic_info, :update_basic_info, :edit_overwork_request, :update_overwork_request]
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy, :edit_basic_info, :update_basic_info]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: [:index, :destroy, :edit_basic_info, :update_basic_info, :working_employee_list]
  before_action :set_one_month, only: [:show, :check]
  before_action :ensure_correct_user, only: [:show, :check]

  def index
    @users = query.order(:id).page(params[:page])
  end
  
  def import
    # fileはtmpに自動で一時保存される
    User.import(params[:file])
    flash[:success] = 'CSVインポートに成功しました。'
    redirect_to users_url
  end
  

  def show
    # ログインユーザーが管理者の場合、別ページへ移動
    if current_user.admin?
      render :edit_basic_info
    else
      @worked_sum = @attendances.where.not(started_at: nil).count
    end
    
    # 一日分の残業申請を行った勤怠データを取得
    @applications_to_A = Attendance.where(authorizer_user_id: "上長Ａ", application_state: "申請中")
    @applications_to_B = Attendance.where(authorizer_user_id: "上長Ｂ", application_state: "申請中")
    # 一ヵ月分の勤怠申請を行った勤怠データを取得
    @month_applications_A = User.where(month_authorizer: "上長Ａ", onemonth_application_state: "申請中")
    @month_applications_B = User.where(month_authorizer: "上長Ｂ", onemonth_application_state: "申請中")
    # 勤怠変更を行った勤怠データを取得
    @edit_applications_A = Attendance.where(change_authorizer: "上長A", application_edit_state: "なし　")
    @edit_applications_B = Attendance.where(change_authorizer: "上長B", application_edit_state: "なし　")
    
  end
  
  def check
    @worked_sum = @attendances.where.not(started_at: nil).count
    @applications_to_A = Attendance.where(authorizer_user_id: "上長Ａ", application_state: "申請中")
    @applications_to_B = Attendance.where(authorizer_user_id: "上長Ｂ", application_state: "申請中")
  end
  
  def ensure_correct_user
    if
      current_user.superior? 
    elsif
      current_user.id != params[:id].to_i
      flash[:danger] = "編集権限がありません。"
      redirect_to users_url
    end
  end

  def new
    @user = User.new
  end

  def create #新規ユーザー作成の処理
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = '新規作成に成功しました。'
      redirect_to @user
    else
      render :new
    end
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "アカウント情報を更新しました。"
      render :edit
    else
      render :edit      
    end
  end

  def destroy # ユーザーを削除する際の処理
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to @user
  end

  def edit_basic_info
    
  end
  
  
  def edit
    
  end
 
  def update_basic_info
    unless @user.update(works_params)
      flash[:danger] = "無効な入力データがあった為、更新をキャンセルしました。"
      redirect_to users_url and return
    else
      User.where(:id => 1..999).update(works_params)
      flash[:success] = "全ユーザーの基本情報を更新しました。"
    end
    redirect_to users_url
  end
  
  def update_user_info
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "アカウント情報を更新しました。"
      redirect_to users_url
    else
      redirect_to users_url   
    end
  end
  
  def working_employee_list
    @users = User.all.includes(:attendances)
  end
  
  def onemonth_apply
    @user = User.find(params[:id])
    
      if @user.update_attributes(onemonth_apply_params)
        if @user.month_authorizer.present?
          flash[:success] = "今月の勤怠を申請しました"
          redirect_to @user
        else
          flash[:danger] = "所属長を選択してください"
          redirect_to @user
        end  
      end
  end
  
  def onemonth_approval
    @user = User.find(params[:id])
    # 上長Ａあての１ヵ月勤怠申請を全て取得
    @month_applications_A = User.where(month_authorizer: "上長Ａ", onemonth_application_state: "申請中")
    # 名前ごとに分類
    @monthwork_applicationsA = @month_applications_A.group_by do |application|
      User.find_by(id: application.id).name
    end
    # 上長Ｂあての１ヵ月勤怠申請を全て取得
    @month_applications_B = User.where(month_authorizer: "上長Ｂ", onemonth_application_state: "申請中")
  end
  
  def update_onemonth_approval
    @user = User.find(params[:id])
    
      params[:application].each do |id, item|
      @attendance = User.find(id)
      @attendance.update_attributes(item.permit(:check))
      
        if @attendance.check == true
          @attendance.update_attributes(item.permit(:onemonth_application_state))
        elsif @attendance.check == false
          @attendance.update_attributes(item.permit(:check))
        end
      
      end
      flash[:success] = "1ヵ月の勤怠申請を承認 or 否認しました。（※チェックボックスにチェックがついていない項目は反映されません）"
      redirect_to @user
  end
  
  def attendances_edit_log
    @user = User.find(params[:id])
    @edit_data = Attendance.where(application_edit_state: "承認　")
  end
  
  def attendance
    @user = User.find(params[:id])
    # @attendances = @user.attendances.where.not(change_authorizer:"上長A ,上長B" , application_edit_state: "なし　")
    @attendances = @user.attendances
  end
  
  private # strongparameterの設定

    def user_params
      params.require(:user).permit(:name, :email, :affiliation, :employee_number, :uid, :password, :password_confirmation, :basic_work_time, :designated_work_start_time , :designated_work_end_time)
    end

    def works_params
      params.require(:user).permit(:id, :basic_work_time, :designated_work_start_time , :designated_work_end_time)
    end
    
    def onemonth_apply_params
      params.require(:user).permit(:month_authorizer, :onemonth_application_state, :application_month)
    end
    
    
    def query
      if params[:user].present? && params[:user][:name]
        User.where('name LIKE ?', "%#{params[:user][:name]}%")
      else
        User.all
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
    
    # 勤怠基本情報を指定のフォーマットで返します。  
  def format_basic_info(time)
    format("%.2f", ((time.hour * 60) + time.min) / 60.0)
  end
end

app/views/users/_edit_overwork_request.html.erb
<% provide(:class_text, 'basic-info') %>
<% provide(:button_text, '残業を申請する') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h4 class="modal-title">【残業申請】</h1>
    </div>
    
    <div class="modal-body">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= form_with(model: @user, url: update_overwork_request_user_path(@user), local: true, method: :patch) do |f| %>
          <% debugger %>
          <%= render 'shared/error_messages', object: @user %>
          <table class="table table-bordered table-striped table-overwork">
            <thead>
              <tr>
                <th>日付</th>
                <th>曜日</th>
                <th>終了予定時間</th>
                <th>翌日</th>
                <th>業務処理内容</th>
                <th>指示者確認㊞</th>
              </tr>
            </thead>
            
            <tbody>
              <tr>
                <td class="table-overwork"></td>
                <td></td>
                <td>
                  <%= f.text_field :name, class: "form-control" %></td>
                <td></td>
                <td></td>
                <td></td>
              </tr>
            </tbody>
          </table>

            <div class="mordal-footer">
              <%= f.submit yield(:button_text), class: "btn btn-primary btn-#{yield(:class_text)}" %>
            </div>
         
          <% end %>
        </div>
      </div><!-- row -->
    </div><!-- modal-body -->
    
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class: "form-control" %>
  
  <%= f.label :affiliation, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :affiliation, class: "form-control" %>

  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>

app/views/users/_onemonth_approval.html.erb
<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h4 class="modal-title"></h4>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-12">
          
        <% if @user.id == 2 %>  
          <%= form_with(model: @user, url: update_onemonth_approval_user_path(@user.id), local: true, method: :patch) do |f| %>
            <%= render 'shared/error_messages', object: @user %>
            
            <% @monthwork_applicationsA.each do |name, applications| %>
            
              <table class="table table-bordered table-striped table-approval">
                <p><%= name %>からの勤怠申請</p>
                <thead>
                  <tr>
                    <th>月</th>
                    <th>指示者確認㊞</th>
                    <th>変更</th>
                    <th>勤怠を確認する</th>
                  </tr>
                </thead>
                
                <tbody>
                  <% applications.each do |application| %>
                    <%= fields_for("application[]", application) do |f| %>
                    <tr>
                      <td><%= application.application_month.month %>月</td>
                      <td><%= f.select :onemonth_application_state, User.onemonth_application_states.keys.to_a, { include_blank: false }, class: "form-control" %></td>
                      <td><%= f.check_box :check %></td>
                      <td><%= link_to "確認", check_user_path(application.id), class: "btn btn-primary" %></td>
                    </tr>
                    <% end %>
                  <% end %><!-- applications.each do -->
                </tbody>
              </table>
              
            <% end %><!-- @monthwork_applicationsA -->
         
          <div class="center">
          <%= f.submit "申請を反映する", class: "btn btn-primary btn-block" %>
          </div>
          <% end %><!-- form_with -->
          
      <% end %><!-- @user.id == 2 -->
      
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/edit_basic_info.html.erb
<% provide(:title, "Edit Basic Info") %>


<h1>基本情報の修正</h1>
    

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<% require 'rounding' %>



<div>
  <table class="table table-bordered table-condensed user-table">
    <tr>
      <td>
        <%= link_to "←", user_path(date: @first_day.prev_month), class: "btn btn-info" %>
        <%= l(@first_day, format: :middle) %>　時間管理表
        <%= link_to "→", user_path(date: @first_day.next_month), class: "btn btn-info" %>
      </td>
      <td style="height:20px; line-height:20px;">
        指定勤務開始時間　<%= format_basic_info(@user.designated_work_start_time) %><br>
        指定勤務終了時間　<%= format_basic_info(@user.designated_work_end_time) %>
      </td>
      <td colspan="3" style="vertical-align:middle;">基本時間　<%= format_basic_info(@user.basic_work_time) %></td>
      <td style="vertical-align:middle;">初日　<%= l(@first_day, format: :short2) %></td>
    </tr>

    <tr>
      <td>所属　<%= @user.affiliation.present? ? @user.affiliation : "未所属" %></td>
      <td>氏名　<%= @user.name %></td>
      <td>コード</td>
      <td><%= @user.id %></td>
      <td>出勤日数　<%= @worked_sum %>日</td>
      <td>締め　<%= l(@last_day, format: :short2) %></td>
    </tr>
  </table>
</div>

<% if @user.superior == true %>
  <div class="oshirase">
    
    <% if @user.id == 2 && @month_applications_A.count > 0 %>
      <%= link_to "【所属長承認申請のお知らせ】", onemonth_approval_user_path(date: @first_day), remote: true %>
      <span style="border: 2px solid red; color: red;"><%= "#{@month_applications_A.count}件の通知があります" %></span><br>
    <% elsif @user.id == 3 && @month_applications_B.count > 0 %>
      <%= link_to "【所属長承認申請のお知らせ】", onemonth_approval_user_path(date: @first_day), remote: true %>
      <span style="border: 2px solid red; color: red;"><%= "#{@month_applications_B.count}件の通知があります" %></span><br>
    <% else %>
     【所属長承認申請のお知らせ】<br>
    <% end %>
 
    <% if @user.id == 2 && @edit_applications_A.count > 0 %>
      <%= link_to "【勤怠変更申請のお知らせ】", edit_changework_approval_user_attendance_path(@user), remote: true %>
      <span style="border: 2px solid red; color: red;"><%= "#{@edit_applications_A.count}件の通知があります" %></span><br>
    <% elsif @user.id == 3 && @edit_applications_B.count > 0 %>
      <%= link_to "【勤怠変更申請のお知らせ】", edit_changework_approval_user_attendance_path(@user), remote: true %>
      <span style="border: 2px solid red; color: red;"><%= "#{@edit_applications_B.count}件の通知があります" %></span><br>
    <% else %>
     【勤怠変更申請のお知らせ】<br>
    <% end %>
  
    <% if @user.id == 2 && @applications_to_A.count > 0 %>
      <%= link_to "【残業申請のお知らせ】", edit_overwork_approval_user_attendance_path(@user), remote: true %>
      <span style="border: 2px solid red; color: red;"><%= "#{@applications_to_A.count}件の通知があります" %></span>
    <% elsif @user.id == 3 && @applications_to_B.count > 0 %>
      <%= link_to "【残業申請のお知らせ】", edit_overwork_approval_user_attendance_path(@user), remote: true %>
      <span style="border: 2px solid red; color: red;"><%= "#{@applications_to_B.count}件の通知があります" %></span>
    <% else %>
    【残業申請のお知らせ】
    <% end %>
    
  </div>
<% end %>

<div class="btn-users-show">
  <%= link_to "勤怠を編集", attendances_edit_one_month_user_path(date: @first_day), class: "btn btn-primary" %>
  <%= link_to "CSV出力", attendance_user_path(format: :csv), class: "btn btn-primary" %><br>
  <p style="margin:5px 0;">
  <%= link_to "勤怠修正ログ（承認済）", attendances_edit_log_user_path(@user), class: "btn btn-primary" %></p>
</div>

<div>
  <table class="table table-bordered table-striped table-condensed table-hover table-margin" id="table-attendances">
    <thead>
        <tr>
        <th rowspan="3">残業申請</th>
        <th rowspan="3">日付</th>
        <th rowspan="3">曜日</th>
        <th colspan="8">【実績】</th>
        <th colspan="5">所定外勤務</th>
        </tr>
        
        <th colspan="3">出社</th>
        <th colspan="3">退社</th>
        <th rowspan="2">在社時間</th>
        <th rowspan="2">備考</th>
        <th colspan="2">終了予定時間</th>
        <th rowspan="2">時間外時間</th>
        <th rowspan="2">業務処理内容</th>
        <th rowspan="2">指示者確認㊞</th>
      </tr>
      
      <tr>
        
        <th><!-- 出勤ボタン用空欄 --></th>
        <th>時</th>
        <th>分</th>
        <th><!-- 退勤ボタン用空欄 --></th>
        <th>時</th>
        <th>分</th>
        <th>時</th>
        <th>分</th>
     
      </tr>
      
      
    </thead>

    <tbody>
      <% @attendances.each do |day| %>

        <tr>
          <td><%= link_to "残業申請", edit_overwork_request_user_attendance_path(@user.id, day), remote: true, class: "btn btn-primary" %></td>
          <td><%= l(day.worked_on, format: :short) %></td><!-- 日付 -->
          <td>
            <% if day.worked_on.wday == 0 %>
              <font color="red">日</font>
            <% elsif day.worked_on.wday == 6 %>
              <font color="blue">土</font>
            <% else %>
              <%= $days_of_the_week[day.worked_on.wday] %>
            <% end %>
          </td><!-- 曜日 -->
          
          <td><!-- 出退勤用ボタン -->
         
            <% if btn_text = attendance_state(day) %>
              <%= link_to "#{btn_text}", user_attendance_path(@user, day), method: :patch, class: "btn btn-primary btn-attendance" %>
            <% end %>
          </td>
          <td><%= l(day.started_at, format: :hour) if day.started_at.present? %></td><!-- 出社の時 -->
          <td><%= l(day.started_at.floor_to(15.minutes), format: :min) if day.started_at.present? %></td><!-- 出社の分 -->
        
          <td><!-- 出退勤用ボタン -->
            <% if btn_text = attendance_state2(day) %>
              <%= link_to "#{btn_text}", user_attendance_path(@user, day), method: :patch, class: "btn btn-primary btn-attendance" %>
            <% end %>
          </td>
          
          <td><%= l(day.finished_at, format: :hour) if day.finished_at.present? %></td><!-- 退社の時 -->
          <td><%= l(day.finished_at.floor_to(15.minutes), format: :min) if day.finished_at.present? %></td><!-- 退社の分 -->
        
          <td><!-- 在社時間 -->
            <% if day.started_at.present? && day.finished_at.present? %>
              <% if day.next_day2? %>
                <% day.finished_at = day.finished_at+1.day %>
              <% else %>
              <% end %>
              <%= str_times = working_times(day.started_at.floor_to(15.minutes), day.finished_at.floor_to(15.minutes)) %>
              
              <% @total_working_times = @total_working_times.to_f + str_times.to_f %>
            <% end %>
          </td>
          <td>
            <%= day.note %>
          </td>
          <td><%= l(day.scheduled_end_time, format: :hour) if day.scheduled_end_time.present? %></td>
          <td><%= l(day.scheduled_end_time, format: :min) if day.scheduled_end_time.present? %></td>
          <td>
            <% if day.scheduled_end_time.present? %>
              <% if day.next_day == true %>
                <%= format_basic_info(day.scheduled_end_time).to_f + format_basic_info(@user.designated_work_end_time - 12.hour).to_f %>
              <% else %>
                <%= format_basic_info(day.scheduled_end_time).to_f - format_basic_info(@user.designated_work_end_time).to_f %>
              <% end %>
            <% end %>
          </td>
          <td><%= day.work_description %></td>
          <td>
            <% if day.authorizer_user_id == "上長Ａ" && day.application_state == "申請中" %>
              <%= "上長Ａに残業申請中" %>
            <% elsif day.authorizer_user_id == "上長Ａ" && day.application_state == "承認" %>
              <%= "残業承認済" %>
            <% elsif day.authorizer_user_id == "上長Ａ" && day.application_state == "否認" %>
              <%= "残業否認" %>
            <% elsif day.authorizer_user_id == "上長Ｂ" && day.application_state == "申請中" %>
              <%= "上長Ｂに残業申請中" %>
            <% elsif day.authorizer_user_id == "上長Ｂ" && day.application_state == "承認" %>
              <%= "残業承認済" %>
            <% elsif day.authorizer_user_id == "上長Ｂ" && day.application_state == "否認" %>
              <%= "残業否認" %>
            <% end %><br>
            
             <% if day.change_authorizer == "上長A" && day.application_edit_state == "なし　" %>
              <%= "上長Ａに勤怠変更申請中" %>
            <% elsif day.change_authorizer == "上長A" && day.application_edit_state == "承認　" %>
              <%= "勤怠変更承認済" %>
            <% elsif day.change_authorizer == "上長A" && day.application_edit_state == "否認　" %>
              <%= "勤怠変更否認" %>
            <% elsif day.change_authorizer == "上長B" && day.application_edit_state == "なし　" %>
              <%= "上長Ｂに勤怠変更申請中" %>
            <% elsif day.change_authorizer == "上長B" && day.application_edit_state == "承認　" %>
              <%= "勤怠変更承認済" %>
            <% elsif day.change_authorizer == "上長B" && day.application_edit_state == "否認　" %>
              <%= "勤怠変更否認" %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
    
    
    <tfoot>
      
      <tr>
        <td rowspan="2"></td>
        <td colspan="2">累計日数</td>
        <td colspan="6">総合勤務時間</td>
        <td colspan="1">在社時間合計</td>
        <td rowspan="2"></td>
        <td rowspan="2"></td>
        <td rowspan="2"></td>
        <td rowspan="2"></td>
        <td rowspan="2"></td>
        <td rowspan="2">
          <%= form_with(model: @user, url: onemonth_apply_user_path(@user.id), local: true, method: :patch) do |f| %>
            <p>
              <% if @user.onemonth_application_state == "申請中" && @user.month_authorizer == "上長Ａ" %>
              所属長承認　上長Ａに申請中
              <% elsif @user.onemonth_application_state == "承認" && @user.month_authorizer == "上長Ａ" %>
              所属長承認　承認済
              <% elsif @user.onemonth_application_state == "否認" && @user.month_authorizer == "上長Ａ" %>
              所属長承認　否認
              <% elsif @user.onemonth_application_state == "申請中" && @user.month_authorizer == "上長Ｂ" %>
              所属長承認　上長Ｂに申請中
              <% elsif @user.onemonth_application_state == "承認" && @user.month_authorizer == "上長Ｂ" %>
              所属長承認　承認済
              <% elsif @user.onemonth_application_state == "否認" && @user.month_authorizer == "上長Ｂ" %>
              所属長承認　否認
              <% else %>
              所属長申請　未
              <% end %>
            </p>
              
            <p>
              <% if @user.id == 2 %>
                <%= f.select :month_authorizer, User.month_authorizers.keys.to_a, { include_blank: true, disabled: "上長Ａ" }, class: "form-control" %>
              <% elsif @user.id == 3 %>
                <%= f.select :month_authorizer, User.month_authorizers.keys.to_a, { include_blank: true, disabled: "上長Ｂ" }, class: "form-control" %>
              <% else %>
                <%= f.select :month_authorizer, User.month_authorizers.keys.to_a, { include_blank: true }, class: "form-control" %>
              <% end %>
            </p>
            <%= f.hidden_field :application_month, {value: @first_day} %>
            <%= f.hidden_field :onemonth_application_state, {value: '申請中'} %>
            <%= f.submit "申請", class: "btn btn-primary btn-block" %>
            
          <% end %>
          </td>
      </tr>
      <tr>
        <td colspan="2"><%= @attendances.count %></td>
        <td colspan="6"><%= format_basic_info(@user.designated_work_start_time).to_f * @worked_sum %></td><!-- 総合勤務時間 -->
        <td colspan="1"><%= format("%.2f", @total_working_times.to_f) %></td><!-- 累計在社時間 -->
        
      </tr>
    </tfoot>    
  
    
    
  </table>
</div>

<!--モーダルウインドウ表示-->
<div id="edit_overwork_request" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="edit_overwork_approval" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="onemonth_approval" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="edit_changework_approval" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>