config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'static_pages#top'
  get '/signup', to: 'users#new'

  # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  # 出勤社員一覧
  get 'working_employee_list', to: 'users#working_employee_list'
  
  # 拠点
  get 'bases', to: 'bases#index'
  get 'base_info', to: 'bases#base_info'
  get 'edit_base_info', to: 'bases#edit_base_info'
  get '/new', to: 'bases#new'
  post '/new', to: 'bases#create'
  delete '/destroy', to: 'bases#destroy'
  patch '/update_base_info', to: 'bases#update_base_info'
 
  
  #リソース
  resources :users do
    collection { post :import }
  end
  
  resources :users do
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      patch 'update_user_info'
      get 'attendances_edit_log'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
      patch 'onemonth_apply'
      get 'onemonth_approval'
      patch 'update_onemonth_approval'
      # 勤怠確認ページ
      get 'check'
      # CSV出力
      get 'attendance'
    end
    resources :attendances do
      member do
        get 'edit_overwork_request'
        patch 'update_overwork_request'
        get 'edit_overwork_approval'
        patch 'update_overwork_approval'
        get 'edit_changework_approval'
        patch 'update_changework_approval'
      end
    end
  end
end

app/controllers/bases_controller.rb
class BasesController < ApplicationController
before_action :admin_user, only: [:index, :destroy, :base_info, :edit_base_info, :update_base_info]


  def index
    @bases = Base.all
  end
  
  def base_info
  end
  
  def new
    @base = Base.new
  end
  
  def create
    @base = Base.new(base_params)
    if @base.save
      flash[:success] = '拠点を追加しました。'
      redirect_to bases_url
    else
      redirect_to bases_url
    end
  end
  
   def destroy # 拠点を削除する際の処理
    @base = Base.find(params[:id])
    @base.destroy
    flash[:success] = "#拠点データを削除しました。"
    redirect_to bases_url
   end
  
  def edit_base_info
    @base = Base.find(params[:id])
  end
  
  def update_base_info
    @base = Base.find(params[:id])
    if @base.update_attributes(base_params)
      flash[:success] = '拠点データを修正しました。'
      redirect_to bases_url
    end
  end
  
  private # strongparameterの設定

    def base_params
      params.require(:base).permit(:basenumber, :basename, :basetype)
    end
end

app/helpers/bases_helper.rb
module BasesHelper
end

app/views/bases/_base_info.html.erb
<% provide(:button_text, '追加する') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h1 class="modal-title">拠点情報の追加</h1>
    </div>
    
    <div class="modal-body">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= form_with(scope: :base, url: new_path(@base), local: true) do |f| %>
            
            <%= f.label :basenumber, "拠点番号" ,class: "label-base-info" %>
            <%= f.number_field :basenumber, class: "form-control" %>
            
            <%= f.label :basename, "拠点名" ,class: "label-base-info" %>
            <%= f.text_field :basename, class: "form-control" %>
            
            <%= f.label :basetype, "拠点種類" ,class: "label-base-info" %>
            <%= f.text_field :basetype, class: "form-control" %>

            <div class="center">
              <%= f.submit yield(:button_text), class: "btn btn-primary btn-base-info" %>
             
            </div>
          <% end %>
        </div>
      </div>
    </div>
    
    <div class="modal-footer">
       <button type="button" class="btn btn-default" data-dismiss="modal">
        閉じる
       </button>
    </div>
  </div>
</div>

app/views/bases/_edit_base_info.html.erb
<% provide(:button_text, '修正する') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h1 class="modal-title">拠点情報の修正</h1>
    </div>
    
    <div class="modal-body">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= form_with(scope: :base, url: update_base_info_path(id: @base), method: :patch, local: true) do |f| %>
            
            <%= f.label :basenumber, "拠点番号" ,class: "label-base-info" %>
            <%= f.number_field :basenumber, class: "form-control" %>
            
            <%= f.label :basename, "拠点名" ,class: "label-base-info" %>
            <%= f.text_field :basename, class: "form-control" %>
            
            <%= f.label :basetype, "勤怠種類" ,class: "label-base-info" %>
            <%= f.text_field :basetype, class: "form-control" %>

            <div class="center">
              <%= f.submit yield(:button_text), class: "btn btn-primary btn-base-info" %>
             
            </div>
          <% end %>
        </div>
      </div>
    </div>
    
    <div class="modal-footer">
       <button type="button" class="btn btn-default" data-dismiss="modal">
        閉じる
       </button>
    </div>
  </div>
</div>

app/views/bases/base_info.js.erb
$("#base_info").html("<%= escape_javascript(render 'base_info') %>");
$("#base_info").modal("show");

app/views/bases/edit_base_info.js.erb
$("#edit_base_info").html("<%= escape_javascript(render 'edit_base_info') %>");
$("#edit_base_info").modal("show");

app/views/bases/index.html.erb
<h1>拠点情報一覧</h1>

<table class="table table-bordered table-condensed user-table">
  
  
  <thead>
    <tr>
    <td></td>
    <td></td>
    <td><b>拠点番号</b></td>
    <td><b>拠点名</b></td>
    <td><b>勤怠種類</b></td>
    </tr>
  </thead>
  
  <tbody>
    <% @bases.each do |base| %>   
    <tr>
    <td>
      <% if current_user.admin? %>
        <%= link_to "編集", edit_base_info_path(id: base.id), remote: true, class: "btn btn-primary" %>
      <% end %>
    </td>
    <td>
      <% if current_user.admin? %>
        <%= link_to "削除", destroy_path(id: base.id), method: :delete,
        data: { confirm: "削除してよろしいですか？" }, class: "btn btn-primary" %>
      <% end %>
      
    </td>
    <td><%= base.basenumber %></td>
    <td><%= base.basename %></td>
    <td><%= base.basetype %></td>
    </tr>
    <% end %>
  </tbody>


</table>

<%= link_to "拠点情報の追加", base_info_path , remote: true, class: "btn btn-primary" %>

<!--モーダルウインドウ表示-->
<div id="base_info" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="edit_base_info" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>