config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'static_pages#top'
  get '/signup', to: 'users#new'

  # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  # 出勤社員一覧
  get 'working_employee_list', to: 'users#working_employee_list'
  
  # 拠点
  get 'bases', to: 'bases#index'
  get 'base_info', to: 'bases#base_info'
  get 'edit_base_info', to: 'bases#edit_base_info'
  get '/new', to: 'bases#new'
  post '/new', to: 'bases#create'
  delete '/destroy', to: 'bases#destroy'
  patch '/update_base_info', to: 'bases#update_base_info'
 
  
  #リソース
  resources :users do
    collection { post :import }
  end
  
  resources :users do
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      patch 'update_user_info'
      get 'attendances_edit_log'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
      patch 'onemonth_apply'
      get 'onemonth_approval'
      patch 'update_onemonth_approval'
      # 勤怠確認ページ
      get 'check'
      # CSV出力
      get 'attendance'
    end
    resources :attendances do
      member do
        get 'edit_overwork_request'
        patch 'update_overwork_request'
        get 'edit_overwork_approval'
        patch 'update_overwork_approval'
        get 'edit_changework_approval'
        patch 'update_changework_approval'
      end
    end
  end
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  require 'rounding'
  belongs_to :user
  # 残業申請状態（0:無 1:申請中 2:承認 3:否認）
  # enum application_state: { nothing: 0, applying: 1, approval: 2, denial: 3 }
  enum application_state: { "なし" => 0, "申請中" => 1, "承認" => 2, "否認" => 3 }
  # 1日分の残業承認者選択
  enum authorizer_user_id: { "上長Ａ" => 1, "上長Ｂ" => 2 }
  # 勤怠編集申請状態（0:無 1:申請中 2:承認 3:否認）
  enum application_edit_state: { "なし　" => 0, "申請中　" => 1, "承認　" => 2, "否認　" => 3 }
  # 勤怠変更の承認者選択
  enum change_authorizer: { "上長A" => 1, "上長B" => 2 }
  

  validates :worked_on, presence: true
  validates :note, length: { maximum: 50 }
  # validates :scheduled_end_time, presence: true
  # validates :authorizer_user_id, presence: true
  # validates :change_authorizer, presence: true
  
  # 出勤時間が存在しない場合、退勤時間は無効 ：カスタムバリデートを定義
  validate :finished_at_is_invalid_without_a_started_at
  
  def finished_at_is_invalid_without_a_started_at # 退勤時間のみ入力している場合のバリデート
    errors.add(:started_at, "が必要です") if started_at.blank? && finished_at.present?
  end
end

# 出勤・退勤時間どちらも存在する時、出勤時間より早い退勤時間は無効 ：カスタムバリデートを定義
# validate :started_at_than_finished_at_fast_if_invalid

# def started_at_than_finished_at_fast_if_invalid
# if started_at.present? && finished_at.present?
#   if !check?
#     errors.add(:started_at, "より早い退勤時間は無効です") if started_at > finished_at
#   end
# end
# end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  
  include AttendancesHelper
  before_action :set_user, only: [:edit_one_month, :update_one_month]
  before_action :logged_in_user, only: [:update, :edit_one_month, :update_one_month]
  before_action :admin_or_correct_user, only: [:edit_one_month, :update_one_month]
  before_action :set_one_month, only: :edit_one_month

  UPDATE_ERROR_MSG = "勤怠登録に失敗しました。やり直してください。"

  def update
    @user = User.find(params[:user_id])
    @attendance = Attendance.find(params[:id])
    # 出勤時間が未登録であることを判定します。
    if @attendance.started_at.nil?
      if @attendance.update_attributes(started_at: Time.current.change(sec: 0), started_at2: Time.current.change(sec: 0))
        
        flash[:info] = "おはようございます！"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    elsif @attendance.finished_at.nil?
      if @attendance.update_attributes(finished_at: Time.current.change(sec: 0), finished_at2: Time.current.change(sec: 0))
        flash[:info] = "お疲れ様でした。"
      else
        flash[:danger] = UPDATE_ERROR_MSG
      end
    end
    redirect_to @user
  end

  def edit_one_month

  end

  
  def update_one_month
    @user = User.find(params[:id])
    if attendances_invalid?
      attendances_params.each do |id, item|
        attendance = Attendance.find(id)
        attendance.update_attributes(item.permit(:next_day2))
        if attendance.next_day2 == true
          attendance.finished_at+1.day
        else
        end
        attendance.update_attributes(item)
      end
      flash[:success] = "勤怠情報を更新しました。"
      redirect_to user_path(@user, params:{first_day: params[:date]})
    else
      flash[:danger] = "出社時間、退社時間、上長選択のいずれかが未入力です"
      redirect_to attendances_edit_one_month_user_url(date: params[:date])
    end
  end
  
  def edit_overwork_request
    @attendance = Attendance.find(params[:id])
    @user = User.find(params[:user_id])
    @youbi = %w{日 月 火 水 木 金 土}
  end
  
  def update_overwork_request
    @attendance = Attendance.find(params[:id])
    @user = User.find(params[:user_id])
      if @attendance.update_attributes(overwork_request_params)
        flash[:success] = "残業を申請しました"
        redirect_to @user
      else
        flash[:danger] = "上長の選択が未入力です"
        redirect_to @user
      end
  end
  
  def edit_overwork_approval
    @attendance = Attendance.find(params[:id])
    @user = User.find(params[:user_id])
    # @users = User.joins(:attendances).where(attendances: { application_state: :applying })
    @youbi = %w{日 月 火 水 木 金 土}
    # 上長Ａあての残業申請を全て取得
    @applications_to_A = Attendance.where(authorizer_user_id: "上長Ａ", application_state: "申請中")
    # 名前ごとに分類
    @overwork_applicationsA = @applications_to_A.group_by do |application|
      User.find_by(id: application.user_id).name
    end
    
    # 上長Ｂあての残業申請を全て取得
    @applications_to_B = Attendance.where(authorizer_user_id: "上長Ｂ", application_state: "申請中")
    # 名前ごとに分類
    @overwork_applicationsB = @applications_to_B.group_by do |application|
      User.find_by(id: application.user_id).name
    end
  end
  
  def update_overwork_approval
    @user = User.find(params[:id])
    
    params[:application].each do |id, item|
    @attendance = Attendance.find(id)
    @attendance.update_attributes(item.permit(:check))
    
      if @attendance.check == true
        @attendance.update_attributes(item.permit(:application_state))
      elsif @attendance.check == false
        @attendance.update_attributes(item.permit(:check))
      end
    
    end
    
    flash[:success] = "勤怠変更申請を承認 or 否認しました。（※チェックボックスにチェックがついていない項目は反映されません）"
    redirect_to @user
  end
           
  def edit_changework_approval
    @attendance = Attendance.find(params[:id])
    @user = User.find(params[:user_id])
    @youbi = %w{日 月 火 水 木 金 土}
    # 上長Ａあての勤怠申請を全て取得
    @applications_to_A = Attendance.where(change_authorizer: "上長A", application_edit_state: "なし　")
    # 名前ごとに分類
    @changework_applicationsA = @applications_to_A.group_by do |application|
    User.find_by(id: application.user_id).name
    end
    # 上長Ｂあての勤怠申請を全て取得
    @applications_to_B = Attendance.where(change_authorizer: "上長B", application_edit_state: "なし　")
    # 名前ごとに分類
    @changework_applicationsB = @applications_to_B.group_by do |application|
    User.find_by(id: application.user_id).name
    end
  end
  
  def update_changework_approval
    @user = User.find(params[:id])
      params[:application].each do |id, item|
      @attendance = Attendance.find(id)
      @attendance.update_attributes(item.permit(:check))
      
        if @attendance.check == true
          @attendance.update_attributes(item.permit(:application_edit_state))
        elsif @attendance.check == false
          @attendance.update_attributes(item.permit(:check))
        end
        
      end
    flash[:success] = "勤怠変更申請を承認 or 否認しました。（※チェックボックスにチェックがついていない項目は反映されません）"
    redirect_to @user
  end
  
  
  private

    # 1ヶ月分の勤怠情報を扱います。
    def attendances_params
      params.require(:user).permit(attendances: [:started_at, :started_at2, :finished_at, :finished_at2, :note, :change_authorizer, :application_edit_state, :next_day ,:next_day2])[:attendances]
    end
    
    def overwork_request_params
      params.require(:attendance).permit(:scheduled_end_time, :next_day, :work_description, :authorizer_user_id, :application_state)
    end
    
    def overwork_approval_params
      params.permit(:application_state)
    end
   
 

    # beforeフィルター

    # 管理権限者、または現在ログインしているユーザーを許可します。
    def admin_or_correct_user
      unless current_user?(@user) || current_user.admin?
        flash[:danger] = "編集権限がありません。"
        redirect_to(root_url)
      end  
    end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
  
  def attendance_state(attendance)
    # 受け取ったAttendanceオブジェクトが当日と一致するか評価します。
    if Date.current == attendance.worked_on
      return '出社' if attendance.started_at.nil? # 出勤時間が空欄の場合、出社ボタンを表示
    end
    # どれにも当てはまらなかった場合はfalseを返します。
    false
  end
  
  def attendance_state2(attendance)
    # 受け取ったAttendanceオブジェクトが当日と一致するか評価します。
    if Date.current == attendance.worked_on
      return '退社' if attendance.started_at.present? && attendance.finished_at.nil?
    end
    # どれにも当てはまらなかった場合はfalseを返します。
    false
  end

  # 出勤時間と退勤時間を受け取り、在社時間を計算して返します。
  def working_times(start, finish)
    format("%.2f", (((finish - start) / 60) / 60.0))
  end
  
  # 不正な値がないか確認する
  def attendances_invalid?
    @user = User.find(params[:id])
    attendances = true
    attendances_params.each do |id, item|
      if item[:started_at].blank? && item[:finished_at].blank?
        next
      elsif item[:started_at].blank? || item[:finished_at].blank?
        attendances = false
        break
      # elsif item[:change_authorizer].blank?
      #   attendances = false
      #   break
      # elsif item[:started_at] > item[:finished_at]
      #   attendances = false
      #   break
      end
    end
    return attendances
  end
  
  def user_attendances_month_date
    @user.attendances.where('worked_on >= ? and worked_on <= ?', @first_day, @last_day).order('worked_on')
  end
end

app/views/attendances/_edit_changework_approval.html.erb
<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h4 class="modal-title"></h4>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-12">
          
        <% if @user.id == 2 %>
          <%= form_with(model: @user, url: update_changework_approval_user_attendance_path(@user.id), local: true, method: :patch) do |f| %>
            <%= render 'shared/error_messages', object: @user %>
              <% @changework_applicationsA.each do |name, applications| %>
              <table class="table table-bordered table-striped table-approval">
                  <p>【 <%= name %> からの勤怠変更申請】</p>
                <thead>
                  <tr>
                    <th rowspan="3">日付</th>
                    <th rowspan="3">曜日</th>
                    <th colspan="4">変更前</th>
                    <th colspan="4">変更後</th>
                    <th rowspan="3">備考</th>
                    <th rowspan="3">指示者確認㊞</th>
                    <th rowspan="3">変更</th>
                    <th rowspan="3">勤怠を確認する</th>
                  </tr>
                  
                  <tr>
                    <th colspan="2">出社</th>
                    <th colspan="2">退社</th>
                    <th colspan="2">出社</th>
                    <th colspan="2">退社</th>
                  </tr>
                  
                  <tr>
                    <th>時</th>
                    <th>分</th>
                    <th>時</th>
                    <th>分</th>
                    <th>時</th>
                    <th>分</th>
                    <th>時</th>
                    <th>分</th>
                  </tr>
                  
                </thead>
                        
                <tbody>
                <% applications.each do |application| %>
                  <%= fields_for("application[]", application) do |f| %>
                    <tr>
                      <td><%= l(application.worked_on, format: :short) %></td>
                      <td><%= $days_of_the_week[application.worked_on.wday] %></td>
                      <td>
                        <% if application.started_at2.nil? %>
                        <% else %>
                          <%= l(application.started_at2, format: :hour) %>
                        <% end %>
                      </td>
                      <td>
                        <% if application.started_at2.nil? %>
                        <% else %>
                          <%= l(application.started_at2, format: :min) %>
                        <% end %>
                      </td>
                      <td>
                        <% if application.finished_at2.nil? %>
                        <% else %>
                          <%= l(application.finished_at2, format: :hour) %>
                        <% end %>
                      </td>
                      <td>
                        <% if application.finished_at2.nil? %>
                        <% else %>
                          <%= l(application.finished_at2, format: :min) %>
                        <% end %>
                      </td>
                      <td><%= l(application.started_at, format: :hour) %></td>
                      <td><%= l(application.started_at, format: :min) %></td>
                      <td><%= l(application.finished_at, format: :hour) %></td>
                      <td><%= l(application.finished_at, format: :min) %></td>
                      <td><%= application.note %></td>
                      <td><%= f.select :application_edit_state, Attendance.application_edit_states.keys.to_a, { include_blank: false }, class: "form-control" %></td>
                      <td><%= f.check_box :check %></td>
                      <td>
                        <%= link_to "確認", check_user_path(application.user_id), class: "btn btn-primary" %>
                      </td>
                    </tr>
                  <% end %><!-- fields_for -->
                <% end %><!-- applications.each do -->
                </tbody>
              </table>
              
         
              <% end %><!-- @overwork_applicationsA -->
            <div class="center">
              <%= f.submit "申請を反映する", class: "btn btn-primary btn-block" %>
            </div>
          <% end %><!-- form_with -->
        <% end %><!-- @user_id == 2 -->
        
        <% if @user.id == 3 %>
          <%= form_with(model: @user, url: update_changework_approval_user_attendance_path(@user.id), local: true, method: :patch) do |f| %>
            <%= render 'shared/error_messages', object: @user %>
              <% @changework_applicationsB.each do |name, applications| %>
              <table class="table table-bordered table-striped table-approval">
                  <p>【 <%= name %> からの勤怠変更申請】</p>
                <thead>
                  <tr>
                    <th rowspan="3">日付</th>
                    <th rowspan="3">曜日</th>
                    <th colspan="4">変更前</th>
                    <th colspan="4">変更後</th>
                    <th rowspan="3">備考</th>
                    <th rowspan="3">指示者確認㊞</th>
                    <th rowspan="3">変更</th>
                    <th rowspan="3">勤怠を確認する</th>
                  </tr>
                  
                  <tr>
                    <th colspan="2">出社</th>
                    <th colspan="2">退社</th>
                    <th colspan="2">出社</th>
                    <th colspan="2">退社</th>
                  </tr>
                  
                  <tr>
                    <th>時</th>
                    <th>分</th>
                    <th>時</th>
                    <th>分</th>
                    <th>時</th>
                    <th>分</th>
                    <th>時</th>
                    <th>分</th>
                  </tr>
                  
                </thead>
                        
                <tbody>
                <% applications.each do |application| %>
                  <%= fields_for("application[]", application) do |f| %>
                    <tr>
                      <td><%= l(application.worked_on, format: :short) %></td>
                      <td><%= $days_of_the_week[application.worked_on.wday] %></td>
                      <td>
                        <% if application.started_at2.nil? %>
                        <% else %>
                          <%= l(application.started_at2, format: :hour) %>
                        <% end %>
                      </td>
                      <td>
                        <% if application.started_at2.nil? %>
                        <% else %>
                          <%= l(application.started_at2, format: :min) %>
                        <% end %>
                      </td>
                      <td>
                        <% if application.finished_at2.nil? %>
                        <% else %>
                          <%= l(application.finished_at2, format: :hour) %>
                        <% end %>
                      </td>
                      <td>
                        <% if application.finished_at2.nil? %>
                        <% else %>
                          <%= l(application.finished_at2, format: :min) %>
                        <% end %>
                      </td>
                      <td><%= l(application.started_at, format: :hour) %></td>
                      <td><%= l(application.started_at, format: :min) %></td>
                      <td><%= l(application.finished_at, format: :hour) %></td>
                      <td><%= l(application.finished_at, format: :min) %></td>
                      <td><%= application.note %></td>
                      <td><%= f.select :application_edit_state, Attendance.application_edit_states.keys.to_a, { include_blank: false }, class: "form-control" %></td>
                      <td><%= f.check_box :check %></td>
                      <td>
                        <%= link_to "確認", check_user_path(application.user_id), class: "btn btn-primary" %>
                      </td>
                    </tr>
                  <% end %><!-- fields_for -->
                <% end %><!-- applications.each do -->
                </tbody>
              </table>
              
         
              <% end %><!-- @overwork_applicationsB -->
            <div class="center">
              <%= f.submit "申請を反映する", class: "btn btn-primary btn-block" %>
            </div>
          <% end %><!-- form_with -->
        <% end %><!-- @user_id == 3 -->
        
        </div>
      </div>
    </div>
  </div>
</div>

app/views/attendances/_edit_overwork_approval.html.erb
<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h4 class="modal-title"></h4>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-12">
          
        <% if @user.id == 2 %>
          <%= form_with(model: @user, url: update_overwork_approval_user_attendance_path(@user.id), local: true, method: :patch) do |f| %>
            <%= render 'shared/error_messages', object: @user %>
              <% @overwork_applicationsA.each do |name, applications| %>
              <table class="table table-bordered table-striped table-approval">
                  <p>【 <%= name %> からの残業申請】</p>
                <thead>
                  <tr>
                    <th>日付</th>
                    <th>曜日</th>
                    <th>終了予定時間</th>
                    <th>指定勤務終了時間</th>
                    <th>時間外時間</th>
                    <th>業務処理内容</th>
                    <th>指示者確認㊞</th>
                    <th>変更</th>
                    <th>勤怠を確認する</th>
                  </tr>
                </thead>
                        
                <tbody>
                <% applications.each do |application| %>
                  <%= fields_for("application[]", application) do |f| %>
                    <tr>
                      <td><%= l(application.worked_on, format: :short) %></td>
                      <td><%= $days_of_the_week[application.worked_on.wday] %></td>
                      <td><%= l(application.scheduled_end_time, format: :time) %></td>
                      <td><%= format_basic_info(@user.designated_work_end_time) %></td>
                      <td>
                        <% if application.scheduled_end_time.present? %>
                          <% if application.next_day == true %>
                            <%= format_basic_info(application.scheduled_end_time).to_f + format_basic_info(@user.designated_work_end_time - 12.hour).to_f %>
                          <% else %>
                            <%= format_basic_info(application.scheduled_end_time).to_f - format_basic_info(@user.designated_work_end_time).to_f %>
                          <% end %>
                        <% end %>
                      </td>
                      <td><%= application.work_description %></td>
                      <td>
                        <%= f.select :application_state, Attendance.application_states.keys.to_a, { include_blank: false }, class: "form-control" %>
                      </td>
                      <td><%= f.check_box :check %></td>
                      <td>
                        <%= link_to "確認", check_user_path(application.user_id), class: "btn btn-primary" %>
                      </td>
                    </tr>
                  <% end %><!-- fields_for -->
                <% end %><!-- applications.each do -->
                </tbody>
              </table>
              
         
              <% end %><!-- @overwork_applicationsA -->
            <div class="center">
              <%= f.submit "申請を反映する", class: "btn btn-primary btn-block" %>
            </div>
          <% end %><!-- form_with -->
        <% end %><!-- @user_id == 2 -->
        
        <% if @user.id == 3 %>
          <%= form_with(model: @user, url: update_overwork_approval_user_attendance_path(@user.id), local: true, method: :patch) do |f| %>
            <%= render 'shared/error_messages', object: @user %>
              <% @overwork_applicationsB.each do |name, applications| %>
              <table class="table table-bordered table-striped table-approval">
                  <p>【 <%= name %> からの残業申請】</p>
                <thead>
                  <tr>
                    <th>日付</th>
                    <th>曜日</th>
                    <th>終了予定時間</th>
                    <th>指定勤務終了時間</th>
                    <th>時間外時間</th>
                    <th>業務処理内容</th>
                    <th>指示者確認㊞</th>
                    <th>変更</th>
                    <th>勤怠を確認する</th>
                  </tr>
                </thead>
                        
                <tbody>
                <% applications.each do |application| %>
                  <%= fields_for("application[]", application) do |f| %>
                    <tr>
                      <td><%= l(application.worked_on, format: :short) %></td>
                      <td><%= $days_of_the_week[application.worked_on.wday] %></td>
                      <td><%= l(application.scheduled_end_time, format: :time) %></td>
                      <td><%= format_basic_info(@user.designated_work_end_time) %></td>
                      <td>
                        <% if application.scheduled_end_time.present? %>
                          <% if application.next_day == true %>
                            <%= format_basic_info(application.scheduled_end_time).to_f + format_basic_info(@user.designated_work_end_time - 12.hour).to_f %>
                          <% else %>
                            <%= format_basic_info(application.scheduled_end_time).to_f - format_basic_info(@user.designated_work_end_time).to_f %>
                          <% end %>
                        <% end %>
                      </td>
                      <td><%= application.work_description %></td>
                      <td>
                        <%= f.select :application_state, Attendance.application_states.keys.to_a, { include_blank: false }, class: "form-control" %>
                      </td>
                      <td><%= f.check_box :check %></td>
                      <td>
                        <%= link_to "確認", check_user_path(application.user_id), class: "btn btn-primary" %>
                      </td>
                    </tr>
                  <% end %><!-- fields_for -->
                <% end %><!-- applications.each do -->
                </tbody>
              </table>
              
         
              <% end %><!-- @overwork_applicationsB -->
            <div class="center">
              <%= f.submit "申請を反映する", class: "btn btn-primary btn-block" %>
            </div>
          <% end %><!-- form_with -->
        <% end %><!-- @user_id == 3 -->
        
        </div>
      </div>
    </div>
  </div>
</div>

app/views/attendances/_edit_overwork_request.html.erb
<% provide(:button_text, '残業を申請する') %>

<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h4 class="modal-title"><%= @user.name %>の残業申請</h4>
    </div>
    <div class="modal-body">
      <div class="row">
        <div class="col-md-10 col-md-offset-1">
          <%= form_with(model: @attendance, url: update_overwork_request_user_attendance_path(@user.id, @attendance.id), local: true, method: :patch) do |f| %>
            <%= render 'shared/error_messages', object: @user %>
            
            <table class="table table-bordered table-striped table-overwork">
              <thead>
                <tr>
                  <th>日付</th>
                  <th>曜日</th>
                  <th>終了予定時間</th>
                  <th>翌日</th>
                  <th>業務処理内容</th>
                  <th>指示者確認㊞</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td><%= l(@attendance.worked_on, format: :short) %></td>
                  <td><%= @youbi[@attendance.worked_on.wday] %></td>
                  <td><%= f.time_field :scheduled_end_time, class: "form-control" %></td>
                  <td><%= f.check_box :next_day %></td>
                  <td><%= f.text_field :work_description, class: "form-control" %></td>
                  <td>
                    <% if @user.id == 2 %>
                      <%= f.select :authorizer_user_id, Attendance.authorizer_user_ids.keys.to_a, { include_blank: true, disabled: "上長Ａ" }, class: "form-control" %>
                    <% elsif @user.id == 3 %>
                      <%= f.select :authorizer_user_id, Attendance.authorizer_user_ids.keys.to_a, { include_blank: true, disabled: "上長Ｂ" }, class: "form-control" %>
                    <% else %>
                      <%= f.select :authorizer_user_id, Attendance.authorizer_user_ids.keys.to_a, { include_blank: true }, class: "form-control" %>
                    <% end %>
                  </td>
                </tr>
              </tbody>
            </table>
            
            <%= f.hidden_field :application_state, {value: '申請中'} %>

            <div class="center">
              <%= f.submit "残業を申請する", class: "btn btn-primary btn-block" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/attendances/edit_changework_approval.js.erb
$("#edit_changework_approval").html("<%= escape_javascript(render 'edit_changework_approval') %>");
$("#edit_changework_approval").modal("show");

app/views/attendances/edit_one_month.html.erb
<% provide(:title, @user.name) %>
<%= form_with(model: @user, url: attendances_update_one_month_user_path(date: @first_day), local: true, method: :patch) do |f| %>
  <div>
    <h1>勤怠編集画面</h1>
    <table class="table table-bordered table-striped table-condensed table-hover" id="table-attendances">
      <thead>
        <tr>
          <th>日付</th>
          <th>曜日</th>
          <th>出社</th>
          <th>退社</th>
          <th>翌日</th>
          <th>在社時間</th>
          <th>備考</th>
          <th>指示者確認㊞</th>
          <!-- <th>承認ステータス</th> -->
        </tr>
      </thead>
      <tbody>
        <% @attendances.each do |day| %>
          <%= f.fields_for "attendances[]", day do |af| %>
            <tr>
              <td><%= l(day.worked_on, format: :short) %></td>
              <td>
                <% if day.worked_on.wday == 0 %>
                <font color="red">日</font>
                <% elsif day.worked_on.wday == 6 %>
                <font color="blue">土</font>
                <% else %>
                <%= $days_of_the_week[day.worked_on.wday] %>
                <% end %>
              </td>
              
              <% if (Date.current < day.worked_on) %>
                <td><%= af.time_field :started_at, readonly: true, class: "form-control" %></td>
                <td><%= af.time_field :finished_at, readonly: true, class: "form-control" %></td>
              <% else %>
                <td><%= af.time_field :started_at, class: "form-control" %></td>
                <td><%= af.time_field :finished_at, class: "form-control" %></td>
              <% end %>
              
              <td><%= af.check_box :next_day2 %></td>
              <td>
                <% if day.started_at.present? && day.finished_at.present? %>
                  <% if day.next_day2? %>
                    <%= working_times(day.started_at, day.finished_at.tomorrow) %>
                  <% else %>
                    <%= working_times(day.started_at, day.finished_at) %>
                  <% end %>
                <% end %>
              </td>
              <td><%= af.text_field :note, class: "form-control" %></td>
              <td>
                <% if @user.id == 2 %>
                  <%= af.select :change_authorizer, Attendance.change_authorizers.keys.to_a, { include_blank: true, disabled: "上長A" }, class: "form-control" %>
                <% elsif @user.id == 3 %>
                  <%= af.select :change_authorizer, Attendance.change_authorizers.keys.to_a, { include_blank: true, disabled: "上長B" }, class: "form-control" %>
                <% else %>
                  <%= af.select :change_authorizer, Attendance.change_authorizers.keys.to_a, { include_blank: true }, class: "form-control" %>
                <% end %>
              </td>
              
            </tr>
            
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="center">
    <%= link_to "キャンセル", user_path(date: @first_day), class: "btn btn-lg btn-default" %>
    <%= f.submit "編集を保存する", class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/attendances/edit_overwork_approval.js.erb
$("#edit_overwork_approval").html("<%= escape_javascript(render 'edit_overwork_approval') %>");
$("#edit_overwork_approval").modal("show");

app/views/attendances/edit_overwork_request.js.erb
$("#edit_overwork_request").html("<%= escape_javascript(render 'edit_overwork_request') %>");
$("#edit_overwork_request").modal("show");